config/routes.rb
Rails.application.routes.draw do
  root 'host_pages#home'

  #query rails repository for the latest, unassigned issues - allow the user to filter the results by component(ActiveRecords etc, Order the results by comment counts, most to least, least to most )
  

  #query rails repo for the latest, unassigned issues
  scope host: 'https://api.github.com/repos/rails/rails/issues'  do 
  	get 'rails_issues' => 'host_pages_#issues', as: :rails_issues
  end

  scope host: 'https://api.github.com/repos/rails/rails/labels' do 
  	get 'rails_labels' => 'host_pages_#rails_components', as: :rails_labels
  end

   scope host: 'https://api.github.com/repos/rails/rails/issues/state=open/comments' do 
  	get 'rails_comments' => 'host_pages_#comments', as: :rails_comments
  end
  #get '/octocat', to: 'https://api.github.com/repos/octocat/Hello-World'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
end

app/controllers/host_pages_controller.rb
class HostPagesController < ApplicationController
  require 'net/http'
  require  'json'

  def home
    url = 'https://api.github.com/repos/rails/rails/issues/state=open' 
    uri = URI(url)
    response = Net::HTTP.get(uri)
    @open_issues = JSON.parse(response)
  end

  def issues
    url = 'https://api.github.com/repos/rails/rails/issues/state=open'   	
  	uri = URI(url)
  	response = Net::HTTP.get(uri)
  	@data = JSON.parse(response)
  end

  def rails_components
    url = 'https://api.github.com/repos/rails/rails/issues/state=open/labels'     
    uri = URI(url)
    response = Net::HTTP.get(uri)
    @labels = JSON.parse(response)
  end

  def comments
    url = 'https://api.github.com/repos/rails/rails/issues/state=open/comments'     
    uri = URI(url)
    response = Net::HTTP.get(uri)
    @comments = JSON.parse(response)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/host_pages_helper.rb
module HostPagesHelper
end

app/views/host_pages/_git_comments.html.erb
<div class="page-content">
<h2 class="page-header" id="git-header"> Comments </h2>

<div id="comment-opts">
</div>

<div id="comment-content">
</div>

</div>

app/views/host_pages/_rails_components.html.erb
<div class="page-content">
<h2 class="page-header" id="rails-header"> Rails Components </h2>
<div id="rc-opts">
</div>
<div id="rc-content">
</div>
</div>

app/views/host_pages/comments.html.erb
<div class="page-content">
<h2 class="page-header" id="git-header"> Comments </h2>

<% for c in @comments %>
<div id="comment-opts">
	<p><%= c %></p>
</div>

<div id="comment-content">
	<p>Number of Comments <%= @comments.length %></p>
</div>
<% end %>
</div>

app/views/host_pages/home.html.erb
<div class="page-content">
	<div class="home-content" id="home-welcome">
		<%= image_tag("railsIcon-01.png", :id => 'home-logo' )%>
		<%= link_to 'Open Unassigned Rails Issues', rails_issues_path, :id=>"home-bttn" %>
		<%= link_to 'Rails Components', rails_labels_path, :id=>"show-rails-issues", :class=>"options" %></div>
	</div>

	<div class="home-content" id="issue-count">
		<div id="issue-highlight"> </div>
		<%= image_tag("gitIcon-01.png", :id => 'git-img' )%>
		<p id="number-of-issues"><%= @open_issues.length %><br>Open Issues</p>
		<%= link_to 'Git Comments', rails_comments_path, :id => "show-git-comments", :class => "options" %> 
	</div>

	<div class="display-issues" id="rails-components">
		<%= render 'rails_components' %>	
	</div>

	<div class="display-issues" id="comments">
		<%= render 'git_comments' %>
	</div>

</div>

app/views/host_pages/issues.html.erb
<p> Rails Currently has </p>
<p><%= @data.length%></p>
<p> Open Issues </p>

app/views/host_pages/rails_components.html.erb
<div class="page-content">
<h2 class="page-header" id="rails-header"> Rails Components </h2>
<div id="rc-opts">
<% for l in @labels %>
<% l = l.to_s%>
<% if l["name"]== 'actioncable' %> 
   		<p class="labels-class" id="ac"> ActionCable</p>
         <% @ac = l %>
<% elsif l["name"] == 'actionmailer' %>
	<p class="labels-class" id="am"> ActionMailer </p>
      <% @am = l %>
<% elsif l["name"] == 'actionpack' %>
	<p class="labels-class" id="ap"> ActionPack </p>
      <% @ap = l %>
<% elsif l["name"] == 'actionview' %>
	<p class="labels-class" id="av"> ActionView </p>
   <% @av = l %>

<% elsif l["name"] == 'assetpipeline' %>
   <p class="labels-class" id="avp"> Asset Pipeline </p>
   <% @actipipe = l %>

<% elsif l["name"] == 'activejob' %>
	<p class="labels-class" id="avj"> ActiveJob </p>
   <% @avij = l %>

<% elsif l["name"] == 'activemodel' %>
   <p class="labels-class" id="avm"> ActiveModel </p>
   <% @acmodel = l %>

<% elsif l["name"] == 'activestorage' %>
   <p class="labels-class" id="as"> ActiveStorage </p>
   <% @avs = l %>

<% elsif l["name"] == 'activesupport' %>
   <p class="labels-class" id="avs"> ActiveSupport </p>
   <% @actsupp = l %>

<% elsif l["name"] == 'activerecord' %>
   <p class="labels-class" id="avr"> ActiveRecord </p>
   <% @acrec = l %>

<% else %>
   <p style="color: white;"> None Found </p>

</div>


<div id="rc-content">
         <p id="show-rails"> Click to show Rails Components </p>
         <div class="labels-data" id="ac-data">
            <p> ActionCable </p>
            <p><%= @ac %></p>
         </div>
         <div class="labels-data" id="am-data">
            <p> ActionMailer</p>
            <p> <%= @am %></p>
         </div>
          <div class="labels-data" id="ap-data">
            <p> ActionPack</p>
            <p> <%= @ap %></p>
         </div>
         <div class="labels-data" id="av-data">
            <p> ActionView</p>
            <p> <%= @av %></p>
         </div>
         <div class="labels-data" id="avs-data">
            <p> Active Storage </p>
            <p><%= @avs %></p>
         </div>
         <div class="labels-data" id="as-data">
            <p> Active Support </p>
            <p><%= @actsupp %></p>
         </div>
         <div class="labels-data" id="avr-data">
            <p> Active Record </p>
            <p><%= @acrec %></p>
         </div>
         <div class="labels-data" id="avm-data">
            <p> Active Model </p>
            <p><%= @acmodel %></p>
         </div>
         <div class="labels-data" id="avp-data">
            <p> Active Pipeline </p>
            <p><%= @actipipe  %></p>
         </div>
         <div class="labels-data" id="avj-data">
           <p> ActiveJob </p>
           <p><%= @avij %></p>
         </div>
<% end %>
<% end %>
</div>

</div>

app/views/layouts/_header.html.erb
<%= link_to 'CheckOnRails', root_path, :id => 'root-header' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheckOnrails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Source+Sans+Pro|Gloria+Hallelujah&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>